WFScroll
GuerillaStudio/vanillalist pull request #47
Opened 2024-10-06 15:29 UTC by hjvf07

Add WFScroll

2024-10-07 23:13 UTC, TixieSalander commented
Your website https://webfullset.com seems empty and so the demos are in 404

2024-10-07 23:16 UTC, TixieSalander requested changes
Please don't repeat the name in the description field and make its content not so similar to the title

2024-10-07 23:18 UTC, TixieSalander commented on plugins/wfscroll.json
> +    "description":"WFScroll animates elements as you scroll. Just - 7.5 kb.",
Keep it simple, "Animate elements as you scroll. Just 7.5kb" for example

2024-10-07 23:20 UTC, TixieSalander commented on plugins/wfscroll.json
> +    "title":"wfscroll: Animate on scroll",
Since your 2 others plugins have the "wfs" in uppercase, for consistency WFScroll would be better (you even wrote it like that in the description)

2024-10-07 23:24 UTC, TixieSalander commented on plugins/wfsgoto.json
> +    "description":"WFSgoto - A simple plugin for animated transition between page blocks.",
Keep it simple. "Animate transition between page blocs." will do

2024-10-07 23:27 UTC, TixieSalander commented on plugins/wfsnav.json
> +    "description":"WFScroll - Smooth transition to blocks - Class on the active menu item - Closing the mobile menu with further moving",
Keep it simple and explanatory: "Allow a quality navigation experience through smooth scroll to blocks, active state for menu item and auto closing its mobile version:

2024-10-08 01:16 UTC, TixieSalander requested changes
Considering all the previous comments I'll wait before approving this addition. Hope you understand.

2024-10-08 01:40 UTC, TixieSalander approved these changes

2024-10-08 16:16 UTC, hjvf07 commented
Hello.

Regarding the demo site. I want to apologize. We changed the server, which is why the site did not work for a while.
Now the site is working and all links are available.

url_npm - Added this parameter to all files. 
- plugins/wfscroll.json
- plugins/wfsgoto.json
- plugins/wfsnav.json

I didn't understand what you mean by the third point.
https://prnt.sc/D95x7KXMkumt
On the chest that I have given, all the names match.

Best regards,
Roman

2024-10-09 01:49 UTC, TixieSalander commented
> I didn't understand what you mean by the third point.
> https://prnt.sc/D95x7KXMkumt

I was probably aiming for consistency:
1. All plugins except wfscroll had WFS in uppercase: that seems like a typo so I fixed it to be like the 2 others
2. With a goal to limit bloating the pages I now have a preference for titles containing only the plugin's name (the search feature look into title and description anyway)

That being said the website for the demos is back and all the plugins are now available on published and added to each data file so it seems we're good to go.

I promise, when I'll have time (currently very complicated for diverse reasons) I'll finish the new version of the site and will avoid continuing that exhausting back-and-forth process to suggest plugins.

Thank you for your contribution and take good care of those little plugins 🫶

2024-10-09 02:09 UTC, TixieSalander approved these changes
Let's end your suffering and deploy this! 😅

2024-10-09 02:12 UTC, merged